package br.com.monitoramento.weblumio.enums;

public enum ErrorCode {
    INVALID_CREDENTIALS,
    INVALID_USERNAME,
    INVALID_EMAIL,
    INVALID_SENSOR_TYPE,
    INVALID_IDENTIFIER,
    INVALID_DESCRIPTION,
    INVALID_PASSWORD,
    INTERNAL_SERVER_ERROR,
    NOT_FOUND,
    ALREADY_EXISTS,
    UNAUTHORIZED
}
